//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the following link to confirm your email &lt;a href=&quot;[[BaseUrl]]/ConfirmEmail?ValidationId=[[Result]]&amp;Email=[[Email]]&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string ConfirmationBody {
            get {
                return ResourceManager.GetString("ConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email sent....
        /// </summary>
        internal static string ConfirmationSent {
            get {
                return ResourceManager.GetString("ConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durra Confirmation Email.
        /// </summary>
        internal static string DurraEmailConfirmation {
            get {
                return ResourceManager.GetString("DurraEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durra Password Reset.
        /// </summary>
        internal static string DurraPasswordReset {
            get {
                return ResourceManager.GetString("DurraPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed!!!.
        /// </summary>
        internal static string Failed_Transaction {
            get {
                return ResourceManager.GetString("Failed_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;body&gt;
        ///		&lt;p&gt;
        ///		  A transaction has been successfully submitted with the following informaiton: 
        ///		  &lt;div&gt;Item Code : [[ItemCode]] &lt;div&gt;
        ///		  &lt;div&gt;Amount: [[TransactionAmount]] KWD&lt;div&gt; 
        ///		  &lt;div&gt;Reference ID: [[ReferenceID]]&lt;div&gt; 
        ///		  &lt;div&gt;Payment ID: [[PaymentID]] &lt;div&gt; 
        ///		  &lt;div&gt;Merchant track ID: [[MerchantTrackID]] &lt;div&gt; 
        ///&lt;div&gt;For help please contact: 00989987655&lt;/div&gt;
        ///		&lt;/p&gt;
        ///	&lt;body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string KnetEmailConfirmation {
            get {
                return ResourceManager.GetString("KnetEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the following link to change your password &lt;a href=&quot;[[BaseUrl]]/ResetPassword?ValidationId=[[Result]]&amp;Email=[[Email]]&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string PasswordResetBody {
            get {
                return ResourceManager.GetString("PasswordResetBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction created successfully!!!.
        /// </summary>
        internal static string Successfull_Transaction {
            get {
                return ResourceManager.GetString("Successfull_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Cancelled !.
        /// </summary>
        internal static string Transaction_Cancelled {
            get {
                return ResourceManager.GetString("Transaction_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Completed.
        /// </summary>
        internal static string Transaction_Completed {
            get {
                return ResourceManager.GetString("Transaction_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوفر.
        /// </summary>
        internal static string WorkerStatus_Available {
            get {
                return ResourceManager.GetString("WorkerStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محجوز.
        /// </summary>
        internal static string WorkerStatus_Booked {
            get {
                return ResourceManager.GetString("WorkerStatus_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متوفر.
        /// </summary>
        internal static string WorkerStatus_Unavailable {
            get {
                return ResourceManager.GetString("WorkerStatus_Unavailable", resourceCulture);
            }
        }
    }
}
